Mesh face
Game-Engine-4/Game-Engine pull request #38
Opened 2022-05-09 12:57 UTC by NPkhakadze

2022-05-09 13:52 UTC, temopkhakadze approved these changes

2022-05-10 06:05 UTC, DerWaschbar requested changes

2022-05-10 06:05 UTC, DerWaschbar commented on src/main/java/MeshShader/Mesh.java
> +        this.ibo=glGenBuffers();
```suggestion
        this.ibo = glGenBuffers();
```

2022-05-10 06:05 UTC, DerWaschbar commented on src/main/java/MeshShader/Mesh.java
> +        glDrawElements(GL_TRIANGLES,size, GL_UNSIGNED_INT,0);
```suggestion
        glDrawElements(GL_TRIANGLES, size, GL_UNSIGNED_INT,0);
```

2022-05-10 06:05 UTC, DerWaschbar commented on src/main/java/MeshShader/Mesh.java
> +        glBindBuffer(GL_ELEMENT_ARRAY_BUFFER,ibo);
```suggestion
        glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, ibo);
```

2022-05-10 06:05 UTC, DerWaschbar commented on src/main/java/Test/Demo.java
> +        Vertex[] vertices= (new Vertex[]{new Vertex(new Vector3f(-1, -1, 0)),
```suggestion
        Vertex[] vertices = (new Vertex[]{new Vertex(new Vector3f(-1, -1, 0)),
```

2022-05-10 06:05 UTC, DerWaschbar commented on src/main/java/Test/Demo.java
> +          //this.tr.setScale(sinTemp, sinTemp, sinTemp);
```suggestion
          this.tr.setScale(sinTemp, sinTemp, sinTemp);
```

2022-05-10 18:01 UTC, temopkhakadze approved these changes

2022-05-10 19:53 UTC, merged