Test
Game-Engine-4/Game-Engine pull request #41
Opened 2022-05-11 18:39 UTC by LukaViper

2022-05-16 07:39 UTC, DerWaschbar requested changes

2022-05-16 07:39 UTC, DerWaschbar commented on src/main/java/Math/Matrix4x4.java
> +    public Matrix4x4(float[][] m) {
```suggestion
    }
    
    public Matrix4x4(float[][] m) {
```

2022-05-16 07:39 UTC, DerWaschbar commented on src/main/java/Math/Vector2f.java
> +    public  float magnitude() {
```suggestion
    public float magnitude() {
```

2022-05-16 07:39 UTC, DerWaschbar commented on src/main/java/Math/Vector2f.java
> +    public static Vector2f mul(Vector2f v, float sc) {
```suggestion
    }
    
    public static Vector2f mul(Vector2f v, float sc) {
```

2022-05-16 07:39 UTC, DerWaschbar commented on src/main/java/Math/Vector2f.java
>      public float distance(Vector2f other) {
```suggestion
    }
    
    public float distance(Vector2f other) {
```

2022-05-16 07:39 UTC, DerWaschbar commented on src/main/java/Math/Vector2f.java
> +    public static float distance(Vector2f v1, Vector2f v2){
```suggestion
    }
    
    public static float distance(Vector2f v1, Vector2f v2){
```

2022-05-16 07:39 UTC, DerWaschbar commented on src/test/java/Math/QuaternionTest.java
> +        assertEquals(l, q1.length());
```suggestion
        assertEquals(4, new Quaternion(1, 2, 3, 4));
```

2022-05-16 07:39 UTC, DerWaschbar commented on src/test/java/Math/Vector3fTest.java
> +    }
?

2022-05-16 07:39 UTC, DerWaschbar commented on src/test/java/Math/Vector3fTest.java
> +    @Test
```suggestion
    }
    
    @Test
```

2022-05-16 07:39 UTC, DerWaschbar commented on src/test/java/Math/Vector3fTest.java
> +    @Test
```suggestion
    }
    
    @Test
```

2022-05-16 07:39 UTC, DerWaschbar commented on src/test/java/Math/Vector3fTest.java
> +        assertEquals(v3, Vector3f.mul(v1, 2));
TODO

2022-05-17 12:07 UTC, closed without merging

2022-05-17 12:08 UTC, LukaViper commented
Needs some changes